apiVersion: apps/v1
kind: Deployment
metadata:
  name: purrfectmatch-backend
  namespace: purrfectmatch
  labels:
    app: purrfectmatch-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: purrfectmatch-backend
  template:
    metadata:
      labels:
        app: purrfectmatch-backend
    spec:
      containers:
        - name: backend
          image: farazhayder/purrfectmatch-js-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGOURI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: cloud_name
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api_key
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api_secret
            - name: POSTMARK_SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: postmark-secret
                  key: server_token
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
