apiVersion: v1
kind: Service
metadata:
  name: purrfectmatch-backend-service
  namespace: purrfectmatch
  labels:
    app: purrfectmatch-backend
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500 # Choose an available port between 30000-32767
      protocol: TCP
      name: http
  selector:
    app: purrfectmatch-backend
