apiVersion: apps/v1
kind: Deployment
metadata:
  name: purrfectmatch-frontend
  namespace: purrfectmatch
  labels:
    app: purrfectmatch-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: purrfectmatch-frontend
  template:
    metadata:
      labels:
        app: purrfectmatch-frontend
    spec:
      containers:
        - name: frontend
          image: farazhayder/purrfectmatch-js-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://192.168.49.2:30500" # Use your actual Minikube IP
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "100m"
