apiVersion: v1
kind: Service
metadata:
  name: purrfectmatch-frontend-service
  namespace: purrfectmatch
  labels:
    app: purrfectmatch-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: purrfectmatch-frontend
